---
title: "Flare vs NMF models"
output: html_document
date: "2025-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(geosphere)
library(circular)
library(lwgeom)
library(sf)
library(units)
```

# Data
## Trailer data
```{r}
trailer_hourly <- readRDS('../DataProcessing/TrailerProcessed-20240601.rds')
names(trailer_hourly)
```

```{r}
columns <- c('time_utc', 'ch4', 'co', 'co2_ppm', 'nox', 'benzene', 'ethene', 
             'ethane', 'wdr_deg', 'wsp_ms')

trailer_hourly_clean <- trailer_hourly %>% 
  select(all_of(columns)) %>%
  mutate(datetime_utc = as.POSIXct(time_utc, tz = 'UTC', format = "%Y-%m-%d %H:%M:%OS"),
         datetime_mountain = with_tz(as.POSIXct(time_utc, tz = 'UTC', format = "%Y-%m-%d %H:%M:%OS"), 
                                     tzone = "America/Denver")) %>%
  mutate(day_utc = as.Date(format(datetime_utc, '%Y-%m-%d')),
         day_mountain = as.Date(format(datetime_mountain, '%Y-%m-%d'))) %>%
  rename('co2' = 'co2_ppm')
```

```{r}
# Compute daily average
trailer_daily <- trailer_hourly_clean %>% 
  select(-c(time_utc, day_utc, datetime_utc, datetime_mountain)) %>% 
  group_by(day_mountain) %>% 
  summarise(across(!wdr_deg, ~mean(.x, na.rm=T)),
            wdr_deg = as.numeric(mean(circular(wdr_deg, units = "degrees"), na.rm=T))) %>%
  mutate(wdr_deg = if_else(wdr_deg < 0, wdr_deg+360, wdr_deg))

# Compute average measurement from 6pm to 6am
trailer_night_avg <- trailer_hourly_clean %>% 
  filter(hour(ymd_hms(datetime_mountain)) <= 6) %>%
  select(-c(time_utc, day_utc, datetime_utc, datetime_mountain)) %>% 
  group_by(day_mountain) %>% 
  summarise(across(everything(), ~mean(.x, na.rm=T))) %>%
  mutate(wdr_deg = if_else(wdr_deg < 0, wdr_deg+360, wdr_deg))
```

## Well Data
```{r}
Wells <- readRDS('../DataProcessing/WellsProcessed20240601.rds')
```

```{r}
wells_monthly <- Wells %>% group_by(substr(prod_date, 1, 7)) %>% 
  mutate(inv_dist_well = ifelse(1 / distToLovi < 0.01, 0, 1 / distToLovi)) %>%
  summarize(distToLovi_wells = mean(distToLovi),
            inv_dist_wells = mean(inv_dist_well),
            weighted_count_wells = sum(inv_dist_wells) * 100,
            weighted_monthly_oil = sum(monthly_oil * inv_dist_well),
            weighted_monthly_gas = sum(monthly_gas * inv_dist_well),
            monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas)) %>% 
  rename(Month = `substr(prod_date, 1, 7)`)
wells_monthly
```

## Flare Data
```{r}
flaring <- readRDS('../DataProcessing/FlaringProcessed.rds')
```

```{r}
loving_lonlat <- c(-104.1089, 32.2961) 
loving_lonlat_sf <- st_sfc(st_point(loving_lonlat), crs = 4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

flaring <- flaring %>%
  st_as_sf(coords = c('lon', 'lat'), remove = F) %>%
  st_set_crs(4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

flaring_loving_50 <- flaring %>% 
  mutate(distToLovi_flare = c(drop_units(st_distance(flaring, loving_lonlat_sf)))/1000) %>% 
  st_drop_geometry() %>%
  select(c("date", 'time_scan', "distToLovi_flare", "temp_bb", "rhi", "esf_bb", "area_bb", "lon", "lat")) %>%
  filter(distToLovi_flare <= 50)

flaring_loving_50 <- flaring_loving_50 %>%
  mutate(time_scan = force_tz(as.POSIXct(time_scan, format = "%Y-%m-%d %H:%M:%OS"), tzone = 'America/Denver')) %>%
  mutate(hour_scan = format(time_scan, '%H:%M'))
flaring_loving_50
```

```{r}
# summarize a daily count flaring
flaring_daily <- flaring_loving_50 %>% 
  mutate(inv_dist = ifelse(1 / distToLovi_flare < 0.01, 0, 1 / distToLovi_flare)) %>%
  filter(distToLovi_flare <= 100) %>% 
  group_by(date) %>% 
  summarise(temp_bb = mean(temp_bb),
            closest.flare = min(distToLovi_flare),
            distToLovi_flare_mean = mean(distToLovi_flare, na.rm=T),
            inv_dist = mean(inv_dist),
            weighted.count = sum(inv_dist) * 100,
            rhi = mean(rhi),
            esf_bb = mean(esf_bb),
            n_flare_50 = n(),
            n_flare_30 = coalesce(sum(distToLovi_flare <= 30), 0),
            n_flare_20 = coalesce(sum(distToLovi_flare <= 20), 0),
            n_flare_10 = coalesce(sum(distToLovi_flare <= 10), 0),
            n_flare_5 = coalesce(sum(distToLovi_flare <= 5), 0)) %>%
  rename(distToLovi_flare = distToLovi_flare_mean)
```


```{r}
# Compute flare angle
angles <- tibble(st_sfc(st_point(loving_lonlat), crs = 4326), 
                 flaring_loving_50[,c('lon', 'lat')] %>% 
                   st_as_sf(coords = c('lon', 'lat')) %>% 
                   st_set_crs(4326)) %>%
                pivot_longer(cols = everything()) %>% 
                pull(value) %>% # extract coordinates only
                st_geod_azimuth() %>%
                set_units('degrees') %>% # convert to degrees
                drop_units()
angles <- angles[c(T, F)] # keep only odd index, valid pairs
angles <- if_else(angles < 0, angles + 360, angles)
flaring_loving_50$angle <- angles
```

## NMF data
```{r}
nmf_data <- readRDS('result_rfiles/normalized_hourly_data_5c_less_o3.rds')
names(nmf_data)
```
```{r}
nmf_factor_hourly <- nmf_data %>%
  select(time_utc, Factor1, Factor2, Factor3, Factor4, Factor5) %>%
  mutate(datetime_mountain = with_tz(as.POSIXct(time_utc, tz = 'UTC', format = "%Y-%m-%d %H:%M:%OS"), 
                                     tzone = "America/Denver")) %>%
  mutate(day_mountain = as.Date(format(datetime_mountain, '%Y-%m-%d'))) %>%
  select(-time_utc) %>%
  filter(if_all(everything(), ~!is.na(.)))
```

```{r}
nmf_factor_day <- nmf_factor_hourly %>% 
  select(-datetime_mountain) %>%
  group_by(day_mountain) %>% 
  summarise(across(everything(), ~mean(.x, na.rm=T))) 

nmf_factor_night <- nmf_factor_hourly %>% 
  filter(hour(ymd_hms(datetime_mountain)) <= 6) %>%
  group_by(day_mountain) %>% 
  summarise(across(everything(), ~mean(.x, na.rm=T))) %>%
  select(-datetime_mountain)
```


# Full
```{r}
radius <- c(5, 10, 20, 30, 50)

full_merged <- trailer_daily %>%
  left_join(trailer_night_avg, join_by(day_mountain), 
              suffix = c('.day', '.night')) %>%
  left_join(flaring_daily, join_by(day_mountain==date)) %>%
  mutate(yearmonth = format(day_mountain, '%Y-%m')) %>%
  left_join(wells_monthly, join_by(yearmonth == Month)) %>%
  left_join(nmf_factor_day, join_by(day_mountain)) %>%
  left_join(nmf_factor_night, join_by(day_mountain), 
              suffix = c('.day', '.night'))

# Add the flare downwind variables.
for (r in radius) {
  temp <- flaring_loving_50 %>%
    filter(distToLovi_flare <= r)
    
  new_colnames <- paste0(c('flare_wd_day_', 'flare_wd_night_'), r)
  
  flare_is_from_wd <- temp %>% 
    left_join(trailer_daily, join_by(date==day_mountain)) %>%
    left_join(trailer_night_avg, join_by(date==day_mountain), 
              suffix = c('.day', '.night')) %>%
  group_by(date) %>%
  summarise(flare_wd_day = sum(abs(angle - wdr_deg.day) <= 30, na.rm=T),
            flare_wd_night = sum(abs(angle - wdr_deg.night) <= 30, na.rm=T)) %>%
  rename(setNames(c('flare_wd_day', 'flare_wd_night'), new_colnames))
  
  full_merged <- full_merged %>%
    left_join(flare_is_from_wd, join_by(day_mountain==date)) %>%
    mutate(across(new_colnames, ~ coalesce(., 0)))
}
```

```{r}
cat('Buffer radius: \n')
cat(radius)

cat('\n Number of flares from 2023-04-14 to 2024-05-31: \n')

cat(sapply(radius, function(x) sum(full_merged[paste0('n_flare_', x)], na.rm=T)))

cat('\n Number of nights with flares from 2023-04-14 to 2024-05-31: \n')

cat(sapply(radius, function(x) sum(full_merged[paste0('n_flare_', x)] > 0, na.rm=T)))
```

# Analysis
- From here, use `full_merged` for models.
```{r}
names(full_merged)
```

```{r}
# Variables for the model
response <- c('ch4', 'benzene', 'co', 'co2', 'nox', 'ethane', 'ethene', 
              'Factor1', 'Factor2', 'Factor3', 'Factor4', 'Factor5')
predictors_fixed <- c('wdr_deg.night', 'wsp_ms.night', 'weighted_monthly_oil', 
                      'weighted_monthly_gas')

# Can also add 'flare_wd_night' to the vector below
predictors_dist_var <- c('n_flare')
distances <- c(5,10,20,30,50)

# Tibble to store the result
compound_flare_lm_result <- tibble(Compound = character(),
                                   Radius = numeric(),
                                   'Adj R-sq' = numeric(),
                                   'df' = numeric())
for (trailer_compound in response) {
  for (distance in distances) {
    predictors_dist_var_temp <- paste0(predictors_dist_var, paste0('_', distance))
    formula_feature_str <- paste(c(predictors_fixed, predictors_dist_var_temp), collapse = ' + ')
    formula_str <- paste(paste0(trailer_compound, '.night'), formula_feature_str, sep = ' ~ ')
    formula <- as.formula(formula_str)
    
    model <- lm(formula, data = full_merged)
    assign(paste0(trailer_compound, '_count_', distance, 'km'), model)
    summary <- summary(model)
    
    compound_flare_lm_result <- compound_flare_lm_result %>%
      add_row(Compound = trailer_compound,
              Radius = distance,
              'Adj R-sq' = round(summary$adj.r.squared,2),
              'df' = summary$df[2])
  }
}
compound_flare_lm_result
```
```{r}

```

```{r}
# Look at the models specifically
for (trailer_compound in response) {
  for (distance in distances) {
    cat('--------------Compound: ', toupper(trailer_compound), ', Radius: ', distance, '---------------', sep = '')
    print(summary(get(paste0(trailer_compound, '_count_', distance, 'km'))))
  }
}
```

