---
title: "Loving Site Modeling-Gam"
author: "William Zhang"
date: "2023-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE)
```
```{r, include=FALSE}
library(tidyverse)
library(lmtest)
library(vip)
library(car)
library(mgcv)
library(corrplot)
library(leaps)
library(gam)
```

## Reading the data
```{r}
loving_daily <- readRDS("../DataProcessing/Trailer_daily_merge.rds")
loving_hourly <- readRDS("../DataProcessing/Trailer_hourly_merge.rds")
```
```{r}
#
loving_daily$count[is.na(loving_daily$count)] <- 0
loving_hourly$count[is.na(loving_hourly$count)] <- 0
```
```{r}
# creating a dataframe without the flares data
loving_daily_noflares <- loving_daily %>% select(-c(temp_bb,rhi, esf_bb, distToLovi,inv_dist))
loving_hourly_noflares <- loving_hourly %>% select(-c(temp_bb,rhi, esf_bb, distToLovi,inv_dist))
```

```{r}
# correlation matrix
M = cor(loving_hourly %>% select(-c("temp_bb", "rhi", "esf_bb", "distToLovi", "inv_dist",
                  "datetime", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "time_hourly")) %>% na.omit())
corrplot.mixed(M, order="AOE", number.cex = 0.5, font.cex = 0.5)
```
## Modeling
### Fitting on Daily
```{r}
# First we do it for daily

# Define the response variable
response_var <- "radon_pCi_mean"

# Define the names of the columns to exclude
exclude_cols <- c("radon_pCi_mean", "rd_particle_B_mean", "rd_particle_pCi_mean", "radon_B_mean", 
                  "temp_bb", "rhi", "esf_bb", "distToLovi", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "inv_dist","datetime")

# Generate the formula for the GAM model
formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(loving_daily), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(loving_daily), exclude_cols), collapse = "+"))


# Fit the GAM model 
daily_v1 <- mgcv::gam(as.formula(paste0(formula_str, "+s(as.numeric(datetime))")), data = loving_daily)

# View the summary of the GAM model
summary(daily_v1)
```
```{r}
plot(daily_v1)
```
```{r}
# using leaps and regsubset to search for best predictors
# exhaustive
# not including flares and oil&gas variables
daily_exhaust = regsubsets(
  radon_pCi_mean~.-rd_particle_B_mean-rd_particle_pCi_mean-radon_B_mean-monthly_oil-monthly_gas-distToLovi_wells, 
  data = loving_daily_noflares, nvmax=30, method = "exhaustive")
reg_summary = summary(daily_exhaust)
```

```{r}
par(mfrow = c(2,2))

plot(reg_summary$rss, xlab = "Number of Variables", ylab = "RSS", type = "l")
plot(reg_summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")

# We will now plot a red dot to indicate the model with the largest adjusted R^2 statistic.
# The which.max() function can be used to identify the location of the maximum point of a vector
adj_r2_max = which.max(reg_summary$adjr2) #21

# The points() command works like the plot() command, except that it puts points 
# on a plot that has already been created instead of creating a new plot
points(adj_r2_max, reg_summary$adjr2[adj_r2_max], col ="red", cex = 2, pch = 20)

# We'll do the same for C_p and BIC, this time looking for the models with the SMALLEST statistic
plot(reg_summary$cp, xlab = "Number of Variables", ylab = "Cp", type = "l")
cp_min = which.min(reg_summary$cp) # 14
points(cp_min, reg_summary$cp[cp_min], col = "red", cex = 2, pch = 20)

plot(reg_summary$bic, xlab = "Number of Variables", ylab = "BIC", type = "l")
bic_min = which.min(reg_summary$bic) # 11
points(bic_min, reg_summary$bic[bic_min], col = "red", cex = 2, pch = 20)
```
```{r}
# checking coefficients of the variables selected using adjusted R^2
plot(daily_exhaust, scale = "adjr2")
coef(daily_exhaust, 21)
```
```{r}
# checking coefficients of the variables selected using Cp
plot(daily_exhaust, scale = "Cp")
coef(daily_exhaust, 14)
```
```{r}
# checking coefficients of the variables selected using BIC
plot(daily_exhaust, scale = "bic")
coef(daily_exhaust, 11)
```

```{r, eval=FALSE}
# Fit the GAM model with ridge regression
daily_v2 <- mgcv::gam(as.formula(
  paste0(formula_str, "+s(as.numeric(as.Date(datetime)))")
  ), data = loving_daily, method = "REML", select = TRUE, family = gaussian, 
  control = mgcv::gam.control(maxit = 100, trace = TRUE))

# View the summary of the GAM model
summary(daily_v2)
```

### Fitting on Hourly
```{r}
# For hourly

# Define the response variable
response_var <- "radon_pCi"

# Define the names of the columns to exclude
exclude_cols <- c("radon_pCi", "rd_particle_B", "rd_particle_pCi", "radon_B",
                  "t_pump_f", "temp_bb", "rhi", "esf_bb", "distToLovi", 
                  "datetime", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "time_hourly")

# Generate the formula for the GAM model
formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(loving_hourly), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(loving_hourly), exclude_cols), collapse = "+"))


# Fit the GAM model 
hourly_v1 <- gam(as.formula(
  paste0(formula_str, "+s(as.numeric(datetime))", "+s(as.numeric(substr(time_hourly, 12, 13)))")
  ), data = loving_hourly)

# View the summary of the GAM model
summary(hourly_v1)
```

```{r}
# using leaps and regsubset to search for best predictors
# exhaustive
# not including flares and oil&gas variables

# adding a hour variable first
loving_hourly_noflares <- loving_hourly_noflares %>% mutate(hour = as.numeric(substr(time_hourly, 12, 13)))

hourly_exhaust = regsubsets(
  radon_pCi~.-time_hourly -rd_particle_B-rd_particle_pCi-radon_B-monthly_oil-monthly_gas-distToLovi_wells, 
  data = loving_hourly_noflares, nvmax=30, method = "exhaustive")
reg_summary = summary(hourly_exhaust)
```


```{r}
par(mfrow = c(2,2))

plot(reg_summary$rss, xlab = "Number of Variables", ylab = "RSS", type = "l")
plot(reg_summary$adjr2, xlab = "Number of Variables", ylab = "Adjusted RSq", type = "l")

# We will now plot a red dot to indicate the model with the largest adjusted R^2 statistic.
# The which.max() function can be used to identify the location of the maximum point of a vector
adj_r2_max = which.max(reg_summary$adjr2) #25

# The points() command works like the plot() command, except that it puts points 
# on a plot that has already been created instead of creating a new plot
points(adj_r2_max, reg_summary$adjr2[adj_r2_max], col ="red", cex = 2, pch = 20)

# We'll do the same for C_p and BIC, this time looking for the models with the SMALLEST statistic
plot(reg_summary$cp, xlab = "Number of Variables", ylab = "Cp", type = "l")
cp_min = which.min(reg_summary$cp) # 20
points(cp_min, reg_summary$cp[cp_min], col = "red", cex = 2, pch = 20)

plot(reg_summary$bic, xlab = "Number of Variables", ylab = "BIC", type = "l")
bic_min = which.min(reg_summary$bic) # 16
points(bic_min, reg_summary$bic[bic_min], col = "red", cex = 2, pch = 20)
```

```{r}
# checking coefficients of the variables selected using adjusted R^2
plot(hourly_exhaust, scale = "adjr2")
coef(hourly_exhaust, 25)
```
```{r}
# checking coefficients of the variables selected using Cp
plot(hourly_exhaust, scale = "Cp")
coef(hourly_exhaust, 20)
```
```{r}
# checking coefficients of the variables selected using adjusted R^2
plot(hourly_exhaust, scale = "bic")
coef(hourly_exhaust, 16)
```