---
title: "Model Comparisons"
author: "William Zhang"
date: "2023-11-16"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(results = 'hide', echo = FALSE, warning=FALSE, message = FALSE, eval = FALSE)
```

```{r, eval=TRUE}
library(knitr)
library(kableExtra)
library(mgcv)
library(tidyverse)
```

```{r}
daily_rd <- readRDS("daily_rd.rds")
hourly_rd <- readRDS("hourly_rd.rds")

daily_radon <- readRDS("daily_radon.rds")
hourly_radon <- readRDS("hourly_radon.rds")
```

```{r}
# Full model
response_var <- "rd_particle_pCi_mean"
exclude_cols <- c("rd_particle_pCi_mean", "rd_particle_B_mean", "radon_pCi_mean", "radon_B_mean", 
                  "temp_bb", "rhi", "esf_bb", "distToLovi", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "inv_dist", "datetime")
formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(daily_rd), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(daily_rd), exclude_cols), collapse = "+"))

daily_rd_full <- mgcv::gam(as.formula(paste0(formula_str, "+s(as.numeric(datetime))")), data = daily_rd)
summary(daily_rd_full)
```

```{r}
# Fitting a Gam on the adjusted R-squared selected variables
daily_adjr <- mgcv::gam(rd_particle_pCi_mean ~ s(as.numeric(datetime)) + no_mean + co_mean + o3_mean + pressure_altcorr_mean + wsp_mean + relh_mean + co2_ppm_mean + ch4_mean + ethene_mean  + cyclopentane_mean + i.pentane_mean + n.pentane_mean  + isoprene_mean + n.octane_mean + toluene_mean + m.p.xylene_mean + o.xylene_mean, data = daily_rd)

# View the summary of the GAM model
summary(daily_adjr)
```

```{r}
# Fitting a Gam on the cp selected variables
daily_rd_cp <- mgcv::gam(rd_particle_pCi_mean ~ s(as.numeric(datetime)) + o3_mean + wsp_mean + wdr_mean + relh_mean + ch4_mean +
                        ethene_mean + cyclopentane_mean + n.hexane_mean + toluene_mean, data = daily_rd)

# View the summary of the GAM model
summary(daily_rd_cp)
```
```{r}

# Fitting a Gam on the BIC selected variables
daily_rd_bic <- mgcv::gam(rd_particle_pCi_mean ~ o3_mean + wsp_mean + wdr_mean + ch4_mean + cyclopentane_mean + n.hexane_mean, data = daily_rd)

# View the summary of the GAM model
summary(daily_rd_bic)
```
```{r}
response_var <- "radon_pCi_mean"
exclude_cols <- c("radon_pCi_mean", "rd_particle_B_mean", "rd_particle_pCi_mean", "radon_B_mean", 
                  "temp_bb", "rhi", "esf_bb", "distToLovi", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "inv_dist", "datetime")
formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(daily_radon), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(daily_radon), exclude_cols), collapse = "+"))
daily_rad_full <- mgcv::gam(as.formula(paste0(formula_str, "+s(as.numeric(datetime))")), data = daily_radon)
summary(daily_rad_full)
```
```{r}
# Fitting a Gam on the RsqAdj selected variables
daily_rad_adjr <- mgcv::gam( radon_pCi_mean ~ s(as.numeric(datetime)) + o3_mean + temp_f_mean + pressure_altcorr_mean + wsp_mean + wdr_mean + relh_mean + rain_mean + co2_ppm_mean + ch4_mean + ethene_mean + i.butane_mean + n.butane_mean + acetylene_mean + cyclopentane_mean + i.pentane_mean + n.pentane_mean + n.hexane_mean + benzene_mean +  ethyl.benzene_mean + m.p.xylene_mean +  o.xylene_mean, data = daily_radon)

# View the summary of the GAM model
summary(daily_rad_adjr)
```
```{r}
# Fitting a Gam on the Cp selected variables
daily_rad_cp <- mgcv::gam(radon_pCi_mean ~ temp_f_mean + pressure_altcorr_mean + wsp_mean + wdr_mean + relh_mean + rain_mean + co2_ppm_mean + ch4_mean + ethene_mean + i.butane_mean + acetylene_mean + i.pentane_mean + n.pentane_mean + n.hexane_mean + benzene_mean, data = daily_radon)

# View the summary of the GAM model
summary(daily_rad_cp)
```
```{r}
# Fitting a Gam on the BIC selected variables
daily_rad_bic <- mgcv::gam(radon_pCi_mean ~ temp_f_mean + pressure_altcorr_mean + wsp_mean + wdr_mean + relh_mean + co2_ppm_mean + ch4_mean + ethene_mean + acetylene_mean + i.pentane_mean + n.pentane_mean + benzene_mean, data = daily_radon)

# View the summary of the GAM model
summary(daily_rad_bic)
```
```{r, results=TRUE, eval=TRUE}
model_results_daily <- data.frame(
  `Reponse.pCi` = c("Rd-particle", "Rd-particle", "Rd-particle", "Rd-particle", "Radon", "Radon","Radon","Radon"),
  Criteria = c("Full", "R^2_adj", "Cp", "BIC", "Full", "R^2_adj", "Cp", "BIC"), 
  `Rsq.adj` = c(0.719, 0.731, 0.719, 0.656, 0.718, 0.723, 0.691, 0.675),
  `Deviance.Exp` = c("80.2%", "78.2%", "75.5%", "67.2%", "80.2%", "77.5%", "72.6%", "70.5%"),
  Num.Pred = c(38, 17, 10, 6, 38, 22, 15, 12),
  Num.Sig.Pred = c(5, 5, 6, 6, 8, 8, 8, 9),
  Sig.Preds = c("co, o3, ch4, n.octane, toluene", "co, o3, relh, ch4, datetime", "o3, wsp, ch4, n.hexane, toluene,  datetime", "o3, wsp, wdr, ch4, cyclopentane, n.hexane", "wsp, wdr, rain, ch4, ethene, n.pentane, m.p.xylene", "pressure_altcorr, wdr, wsp, rain, ch4, i.pentane, n.pentane, o.xylene", "temp_f, pressure_altcorr, wsp, wdr, rain, ch4, n.pentane, benzene", "temp_f, pressure_altcorr, wsp, wdr, relh, ch4, i.pentane, n.pentane, benzene"),
  `Rsq.adj.with.datetime` = c("-", "-", "-", "0.677", "-", "-", "0.702", "0.703")
)
model_results_daily %>% 
kbl(digits = 3, caption = "<span style='font-size:150%'>Comparisons For Daily Dataset</span>") %>%
  kable_styling() %>% 
  row_spec(c(1, 5), background = "#d1f1eb") %>% 
  row_spec(c(2, 6), background = "#DDDDFF") %>% 
  row_spec(c(3, 7), background = "lightyellow")
```
- Significance threshold taken to be 0.05
- Last column is adding smoothed datetime if the model didn't previous contain it

```{r}
response_var <- "rd_particle_pCi"
exclude_cols <- c("radon_pCi", "rd_particle_B", "rd_particle_pCi", "radon_B",
                  "t_pump_f", "temp_bb", "rhi", "esf_bb", "distToLovi", "inv_dist",
                  "datetime", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "time_hourly", "hour")

formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(hourly_rd), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(hourly_rd), exclude_cols), collapse = "+"))
hourly_rd_full <- mgcv::gam(as.formula(
  paste0(formula_str, "+s(as.numeric(datetime))", "+s(hour)")
  ), data = hourly_rd)

# View the summary of the GAM model
summary(hourly_rd_full)
```
```{r}
# Fitting a Gam on the Rsq-Adj selected variables
hourly_rd_Radj <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + co + no2 + nox + o3 + temp_f + pressure_altcorr + wsp + wdr + relh + solr + co2_ppm + ch4 + ethane + propene + X1_3.butadiene + i.butane + n.butane + acetylene + n.pentane + n.hexane + n.heptane + n.octane + toluene + m.p.xylene + o.xylene + weighted.count + count +s(hour), data = hourly_rd)
summary(hourly_rd_Radj)
```
```{r}
# Fitting a Gam on the Cp selected variables
hourly_rd_cp <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + co + no2 + nox + o3 + temp_f + pressure_altcorr + wsp + wdr + relh + solr + co2_ppm + ch4 + ethane + propene + X1_3.butadiene + i.butane + n.butane + acetylene + n.octane + toluene + m.p.xylene + o.xylene + s(hour) + weighted.count + count, data = hourly_rd)
summary(hourly_rd_cp)
```
```{r}
# Fitting a Gam on the BIC selected variables
hourly_rd_bic <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + co + no2 + nox + o3 + temp_f  + wdr + relh + solr + co2_ppm + ch4 + propene + n.butane + n.octane + toluene +s(hour), data = hourly_rd)

summary(hourly_rd_bic)
```
```{r}
response_var <- "radon_pCi"
exclude_cols <- c("radon_pCi", "rd_particle_B", "rd_particle_pCi", "radon_B",
                  "t_pump_f", "temp_bb", "rhi", "esf_bb", "distToLovi", "inv_dist",
                  "datetime", "monthly_oil", "monthly_gas", "distToLovi_wells",
                  "time_hourly", "hour")
formula_str_s <- paste(response_var, "~", paste(paste0("s(", setdiff(names(hourly_radon), exclude_cols), ")"), collapse = "+"))
formula_str <- paste(response_var, "~", paste(setdiff(names(hourly_radon), exclude_cols), collapse = "+"))
hourly_rad_full <- mgcv::gam(as.formula(
  paste0(formula_str, "+s(as.numeric(datetime))", "+s(hour)")
  ), data = hourly_radon)
summary(hourly_rad_full)
```
```{r}
# Fitting a Gam on the Rsq-adj selected variables
hourly_rad_Radj <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + co + no2 + nox + temp_f + pressure_altcorr + wsp + wdr + relh + co2_ppm + ethane + propene + X1_3.butadiene + i.butane + n.butane + acetylene + cyclopentane + n.pentane + n.hexane + benzene + ethyl.benzene + m.p.xylene + o.xylene + s(hour), data = hourly_radon)

summary(hourly_rad_Radj)
```
```{r}
# Fitting a Gam on the Cp selected variables
hourly_rad_cp <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + no2 + nox + temp_f + pressure_altcorr + wsp + wdr + relh + co2_ppm + ethane + propene + X1_3.butadiene + i.butane + n.butane + acetylene + cyclopentane + n.hexane + n.heptane + benzene +s(hour), data = hourly_radon)

summary(hourly_rad_cp)
```
```{r}
# Fitting a Gam on the BIC selected variables
hourly_rad_bic <- mgcv::gam(radon_pCi~ s(as.numeric(datetime)) + no2 + temp_f + pressure_altcorr + wsp + wdr + relh + co2_ppm + ethane + propene + X1_3.butadiene + n.butane + acetylene + benzene +s(hour), data = hourly_radon)

summary(hourly_rad_bic)
```

```{r, results=TRUE, eval=TRUE}
model_results_hourly <- data.frame(
  `Reponse.pCi` = c("Rd-particle", "Rd-particle", "Rd-particle", "Rd-particle", "Radon", "Radon","Radon","Radon"),
  Criteria = c("Full", "R^2_adj", "Cp", "BIC", "Full", "R^2_adj", "Cp", "BIC"), 
  `Rsq.adj` = c(0.731, 0.623, 0.622, 0.579, 0.631, 0.627, 0.618, 0.616),
  `Deviance.Exp` = c("73.6%", "62.9%", "62.8%", "58.3", "63.7%", "63.2%", "62.3%", "62%"),
  Num.Pred = c(39, 29, 26, 16, 39, 24, 20, 16),
  Num.Sig.Pred = c(23, 19, 20, 11, 23, 20, 18, 15),
  Sig.Preds = c("co, no, no2, nox, o3, pressure_altcorr, wdr, relh, solr, co2_ppm, ch4, ethane, propane, X1_3.butadiene, cyclopentane, n.pentane, benzene, n.octane, toluene, ethyl.benzene, m.p.xylene, datetime, hour", "co, no, no2, o3, pressure_altcorr, wsp, wdr, relh, co2_ppm, ch4, ethane, propane, X1_3.butadiene, acetylene, toluene, m.p.xylene,o.xylene, datetime, hour", "co, no2, o3, temp_f, pressure_altcorr, wsp, wdr, relh, co2_ppm, ch4, ethane, propene, X1_3.butadiene, n.butane, acetylene, toluene, m.p.xylene, o.xylene, datetime , hour", "co, no2, temp_f, wdr, relh, co2_ppm, ch4, n.butane, toluene, datetime, hour", "co, no, no2, nox, temp_f, pressure_altcorr, wsp, wdr, relh, co2_ppm, ch4, ethane, propene, X1_3.butadiene, cyclopentane, acetylene, n.hexane, n.octane, ethyl.benzene, m.p.xylene, o.xylene, datetime, hour", "co, no2, temp_f, pressure_altcorr, wsp, wdr, relh, co2_ppm, ethane, propene, X1_3.butadiene, acetylene, cyclopentene, n.hexane, ethyl.benzene, m.p.xylene, o.xylene, datetime, hour", "no2, temp_f, pressure_altcorr, wsp, wdr, relh, co2_ppm, ethane, propene, X1_3.butadiene, i.butane, n.butane, acetylene, cyclopentane, n.hexane, n.heptane, datetime, hour", "temp_f, pressure_altcorr, wsp, wdr, relh, co2_ppm, ethane, propene, X1_3.butadiene, n.butane, acetylene, benzene, datetime, hour")
)
model_results_hourly %>% 
kbl(digits = 3, caption = "<span style='font-size:150%'>Comparisons For Hourly Dataset</span>") %>%
  kable_styling() %>% 
  row_spec(c(1, 5), background = "#d1f1eb") %>% 
  row_spec(c(2, 6), background = "#DDDDFF") %>% 
  row_spec(c(3, 7), background = "lightyellow")
```
