---
title: "FlaringProcess"
author: "William Zhang"
date: "2023-09-28"
output: html_document
---
## Reading in RDS
```{r}
# library(geosphere)
library(sf)
library(units)
```

```{r}
flaring <- readRDS("../data/loving_vnf/loving200km-vnf_230414-240901.rds")
flaring_v35 <- readRDS("../data/pb_vnf/viirs_filtered_V35.rds")
```

## Filtering and Processing
```{r}
write_csv(flaring_v35, "../data/pb_vnf/flaring_v35.csv")
```

```{r}
# excluding all cooler than 1600 bb
flaring <- flaring %>% filter(temp_bb >= 1600)
```

Distance function, How far each flares are
```{r}
# lon, lat of Loving monitor:  (-104.1089, 32.2961)
# loving_lonlat <- c(-104.1089, 32.2961)
# distance_km_lov <- function(long, lati){
#   start <- c(long, lati)
#   distGeo(start, loving_lonlat) / 1000
# }

# 32.297345,-104.109386
loving_lonlat <- c(-104.1089, 32.2961) 
loving_lonlat_sf <- st_sfc(st_point(loving_lonlat), crs = 4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")
# distance_km_lov <- function(long, lati){
#   start <- c(long, lati)
#   distGeo(start, loving_lonlat) / 1000
# }

flaring <- flaring %>%
  st_as_sf(coords = c('lon', 'lat'), remove = F) %>%
  st_set_crs(4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

flaring_loving <- flaring %>% 
  mutate(distToLovi = c(drop_units(st_distance(flaring, loving_lonlat_sf)))/1000) %>% 
  st_drop_geometry() %>%
  select(c("date", 'time_scan', "distToLovi", "temp_bb", "rhi", "esf_bb", "area_bb", "lon", "lat")) 
```

### Saving
```{r}
saveRDS(flaring_loving, "FlaringProcessed.rds")
```





