---
title: "Merging"
author: "William Zhang, Jerry"
date: "2024-09-06"
output: html_document
---
```{r}
library(tidyverse)
```

```{r}
# Read all the related RDS first
flaring <- readRDS('../data/processed_data/FlaringProcessed20250909.rds')
Trailer <- readRDS('../data/processed_data/TrailerProcessed20250909.rds')
# Weather <- readRDS('WeatherProcessed.rds')
Wells <- readRDS('../data/processed_data/WellsProcessed20250909.rds')
```

## A few processing
```{r}
# Remove Trailer entries where radon_pci or rd_particle_pci is NA
# Trailer <- Trailer[!is.na(Trailer$radon_pCi) & !is.na(Trailer$rd_particle_pCi), ]

# add a daily date and a monthly date
Trailer <- Trailer %>% mutate(day = format(as.POSIXct(time_utc), '%Y-%m-%d'))
Trailer <- Trailer %>% mutate(yearmonth = format(as.POSIXct(time_utc), '%Y-%m'))
```
```{r}
# create a trailer_daily
my_mean <- function(x){
  mean(x, na.rm=TRUE)
}
Trailer_daily <- Trailer %>% group_by(day) %>% 
  summarize_at(vars(-c(time_utc, hour, yearmonth)), list(mean = my_mean))

# add a month variable for that
Trailer_daily <- Trailer_daily %>% mutate(yearmonth = format(as.POSIXct(day), '%Y-%m'))
```
```{r}
# add an inverse distance for flaring
flaring$inv_dist <- ifelse(1 / flaring$distToLovi < 0.01, 0, 1 / flaring$distToLovi)
```
```{r}
# summarize a daily count flaring
flaring_daily <- flaring %>% 
  # weighted_count = sum of inv_distance
  filter(distToLovi <= 100) %>% 
  group_by(date) %>% 
  summarise(temp_bb = mean(temp_bb),
            closest.flare = min(distToLovi),
            distToLovi_mean = mean(distToLovi, na.rm=T),
            inv_dist = mean(inv_dist),
            weighted.count = sum(inv_dist) * 100,
            rhi = mean(rhi),
            esf_bb = mean(esf_bb),
            n_flare_100 = n(),
            n_flare_30 = coalesce(sum(distToLovi <= 30), 0),
            n_flare_20 = coalesce(sum(distToLovi <= 20), 0),
            n_flare_10 = coalesce(sum(distToLovi <= 10), 0),
            n_flare_5 = coalesce(sum(distToLovi <= 5), 0)) %>%
  rename(distToLovi = distToLovi_mean)
```


```{r}
# summarize a monthly count production
wells_monthly <- Wells %>% group_by(substr(prod_date, 1, 7)) %>% 
  summarize(distToLovi_wells = mean(distToLovi),
            monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas)) %>% 
  rename(Month = `substr(prod_date, 1, 7)`)

wells_monthly <- Wells %>% group_by(substr(prod_date, 1, 7)) %>%
  mutate(inv_dist_well = ifelse(1 / distToLovi < 0.01, 0, 1 / distToLovi)) %>%
  summarize(distToLovi_wells = mean(distToLovi),
            inv_dist_wells = mean(inv_dist_well),
            weighted_count_wells = sum(inv_dist_wells) * 100,
            weighted_monthly_oil = sum(monthly_oil * inv_dist_well),
            weighted_monthly_gas = sum(monthly_gas * inv_dist_well),
            monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas)) %>%
  rename(Month = `substr(prod_date, 1, 7)`)

wells_monthly <- Wells %>%
  ungroup() %>%
  mutate(
    Month = substr(prod_date, 1, 7),
    inv_dist_well = ifelse(1 / distToLovi < 0.01, 0, 1 / distToLovi)
  ) %>%
  summarize(
    .by = Month,
    distToLovi_wells = mean(distToLovi, na.rm = TRUE),
    inv_dist_wells = mean(inv_dist_well, na.rm = TRUE),
    weighted_count_wells = sum(inv_dist_well, na.rm = TRUE) * 100,
    weighted_monthly_oil = sum(monthly_oil * inv_dist_well, na.rm = TRUE),
    weighted_monthly_gas = sum(monthly_gas * inv_dist_well, na.rm = TRUE),
    monthly_oil = sum(monthly_oil, na.rm = TRUE),
    monthly_gas = sum(monthly_gas, na.rm = TRUE)
  )
```


## Merging
```{r}
Trailer_hourly_merge <- merge(x = Trailer, 
                              y = flaring_daily,
                              by.x = 'day',
                              by.y = 'date',
                              all.x = TRUE,
                              all.y = FALSE)
Trailer_hourly_merge <- merge(x = Trailer_hourly_merge,
                              y = wells_monthly,
                              by.x = 'yearmonth',
                              by.y = 'Month',
                              all.x = TRUE,
                              all.y = FALSE)
```
```{r}
Trailer_daily_merge <- merge(x = Trailer_daily, 
                              y = flaring_daily,
                              by.x = 'day',
                              by.y = 'date',
                              all.x = TRUE,
                              all.y = FALSE)
Trailer_daily_merge <- merge(x = Trailer_daily_merge,
                              y = wells_monthly,
                              by.x = 'yearmonth',
                              by.y = 'Month',
                              all.x = TRUE,
                              all.y = FALSE)
```

```{r}
# some additional cleaning after merging
Trailer_hourly_merge <- Trailer_hourly_merge %>% select(-c(yearmonth))

Trailer_daily_merge <- Trailer_daily_merge %>% select(-c(yearmonth))
```

```{r}
# make datetime a Date variable
Trailer_hourly_merge <- Trailer_hourly_merge %>% mutate(day = as.Date(day))
Trailer_daily_merge <- Trailer_daily_merge %>% mutate(day = as.Date(day))
```

# Further cleaning
```{r}
# making NA flare_count to 0
Trailer_daily_merge$n_flare_100[is.na(Trailer_daily_merge$n_flare_100)] <- 0
Trailer_hourly_merge$n_flare_100[is.na(Trailer_hourly_merge$n_flare_100)] <- 0
Trailer_daily_merge$weighted.count[is.na(Trailer_daily_merge$weighted.count)] <- 0
Trailer_hourly_merge$weighted.count[is.na(Trailer_hourly_merge$weighted.count)] <- 0
# none flare within 100km
Trailer_daily_merge$closest.flare[is.na(Trailer_daily_merge$closest.flare)] <- 100
Trailer_hourly_merge$closest.flare[is.na(Trailer_hourly_merge$closest.flare)] <- 100
```

## Saving
```{r}
saveRDS(Trailer_hourly_merge, "../data/processed_data/Trailer_hourly_merge_20250909.rds")
saveRDS(Trailer_daily_merge, "../data/processed_data/Trailer_daily_merge_20250909.rds")
```


