---
title: "Methane Comparison"
author: "Jerry Wu"
date: "2025-01-20"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(geosphere)
library(circular)
library(lwgeom)
library(sf)
library(units)
```

```{r}
# Load in trailer Methane
Trailer <- readRDS('TrailerProcessed-20240601.rds')

trailer_comps_wind <- Trailer %>% select(time_utc, ch4, co, co2_ppm, nox, benzene, wdr_deg, wsp_ms) %>%
  mutate(day = as.Date(format(as.POSIXct(time_utc), '%Y-%m-%d'))) %>%
  rename('co2' = 'co2_ppm')
```

```{r}
# # Load in VNF data
# vnf <- readRDS('pb-vnf_20230501-20240601.rds')
# 
# vnf <- vnf %>% 
#   mutate(across(where(is.numeric),  ~ na_if(.x, 999999))) %>% # replace 999999 as missing
#   filter(!(is.na(temp_bb) | is.na(methane_eq))) # keep those not missing temperature
# 
# vnf <- vnf %>%
#   filter(temp_bb >= 1600)
# 
loving_lonlat <- c(-104.1089, 32.2961)
# distance_km_lov <- function(long, lati){
#   start <- c(long, lati)
#   distGeo(start, loving_lonlat) / 1000
# }
# 
# vnf <- vnf %>% 
#   mutate(distToLovi = mapply(distance_km_lov, lon, lat))
# 
# saveRDS(vnf, 'vnf_cleaned_20230501-20240601.rds')
vnf <- readRDS('vnf_cleaned_20230501-20240601.rds')
```

```{r}
# Preprocessing
vnf_200km <- vnf %>%
  filter(distToLovi <= 200)

radius <- c(5, 10, 20, 50, 100)

trailer_compounds <- c('ch4', 'co', 'co2', 'nox', 'benzene')

# Compute daily average
trailer_daily <- trailer_comps_wind %>% 
  select(-time_utc) %>% 
  group_by(day) %>% 
  summarise(across(!wdr_deg, ~mean(.x, na.rm=T)),
            wdr_deg = as.numeric(mean(circular(wdr_deg, units = "degrees"), na.rm=T))) %>%
  mutate(wdr_deg = if_else(wdr_deg < 0, wdr_deg+360, wdr_deg))
  

# Compute average measurement from 6pm to 6am
trailer_night_avg <- trailer_comps_wind %>% 
  filter(hour(ymd_hms(time_utc)) <= 6 ) %>%
  select(-time_utc) %>% 
  group_by(day) %>% 
  summarise(across(everything(), ~mean(.x, na.rm=T))) %>%
  mutate(wdr_deg = if_else(wdr_deg < 0, wdr_deg+360, wdr_deg))

# Compute flare angle
angles <- tibble(st_sfc(st_point(loving_lonlat), crs = 4326), 
                 vnf_200km[,c('lon', 'lat')] %>% 
                   st_as_sf(coords = c('lon', 'lat')) %>% 
                   st_set_crs(4326)) %>%
                pivot_longer(cols = everything()) %>% 
                pull(value) %>% # extract coordinates only
                st_geod_azimuth() %>%
                set_units('degrees') %>% # convert to degrees
                drop_units()
angles <- angles[c(T, F)] # keep only odd index, valid pairs
angles <- if_else(angles < 0, angles + 360, angles)
vnf_200km$angle <- angles

corr_result <- tibble(radius = numeric(), 
                      trailer_compound = character(),
                      flare_count = numeric(),
                      daily_corr = numeric(),
                      nightly_corr = numeric())

vnf_trailer_full <- tibble(date = vnf_200km %>%
    filter(distToLovi <= max(radius)) %>% pull(date) %>% unique()) %>%
    left_join(trailer_daily, 
              join_by(date == day)) %>%
    left_join(trailer_night_avg, 
              join_by(date == day), suffix = c('.day', '.night'))

for (r in radius) {
  # Filter for flares within radius r
  temp <- vnf_200km %>%
    filter(distToLovi <= r)
  
  # For those flares, get average methane_eq then join with trailer data
  # NOTE: since we have a n-to-1 mapping between flares and trailer, 
  # it is difficult to get a single wind difference value for each day.
  # Instead, I will check if there exists a flare in a similar direction as wind
  flare_is_from_wd <- temp %>%
    left_join(trailer_daily, 
              join_by(date == day)) %>%
    left_join(trailer_night_avg, 
              join_by(date == day), suffix = c('.day', '.night')) %>%
    group_by(date) %>%
    summarise(flare_wd_day = sum(abs(angle - wdr_deg.day) <= 30),
              flare_wd_night = sum(abs(angle - wdr_deg.night) <= 30),
              flare_count = length(unique(vnf_id))) %>%
    rename(setNames(c('flare_wd_day', 'flare_wd_night', 'flare_count'), paste0(c('flare_wd_day_', 'flare_wd_night_', 'flare_count_'), r)))

  temp <- temp %>%
    select(date, methane_eq, angle) %>%
    group_by(date) %>%
    summarise(avg_methane_eq = mean(methane_eq)) %>%
    rename(setNames('avg_methane_eq', paste0('avg_methane_eq_', r)))
  
  merged <- temp %>%
    left_join(trailer_daily, 
              join_by(date == day)) %>%
    left_join(trailer_night_avg, 
              join_by(date == day), suffix = c('.day', '.night')) %>%
    left_join(flare_is_from_wd, join_by(date)) %>%
    rename(setNames(paste0('avg_methane_eq_', r), 'ch4_vnf'))
  
  vnf_trailer_full <- vnf_trailer_full %>%
    left_join(temp, join_by(date)) %>%
    left_join(flare_is_from_wd, join_by(date))
              
  corr <- tibble(radius = r, 
                 trailer_compound = trailer_compounds, 
                 flare_count = merged %>% 
                   pull(paste0('flare_count_', r)) %>%
                   sum(),
                 daily_corr = sapply(paste0(trailer_compounds, '.day'), 
                               function(x) cor(merged$ch4_vnf, merged[[x]], 
                                               use = 'complete')),
                 nightly_corr = sapply(paste0(trailer_compounds, '.night'), 
                               function(x) cor(merged$ch4_vnf, merged[[x]], 
                                               use = 'complete')))
  
  corr_result <- rbind(corr_result, corr)
}

knitr::kable(corr_result %>% arrange(trailer_compound, radius), digits = 3)
```
```{r}
ch4_nox_5km <- lm(avg_methane_eq_5 ~ ch4.night + co.night + co2.night + nox.night + benzene.night + wsp_ms.night + flare_wd_night_5 + flare_count_5, data = vnf_trailer_full)
summary(ch4_nox_5km)

ch4_nox_10km <- lm(avg_methane_eq_10 ~ ch4.night + co.night + co2.night + nox.night + benzene.night + wsp_ms.night + flare_wd_night_10 + flare_count_10, data = vnf_trailer_full)
summary(ch4_nox_10km)

ch4_nox_20km <- lm(avg_methane_eq_20 ~ ch4.night + co.night + co2.night + nox.night + benzene.night + wdr_deg.night + wsp_ms.night + flare_wd_night_20 + flare_count_20, data = vnf_trailer_full)
summary(ch4_nox_20km)

ch4_nox_50km <- lm(avg_methane_eq_50 ~ ch4.night + co.night + co2.night + nox.night + benzene.night + wdr_deg.night + wsp_ms.night + flare_wd_night_50 + flare_count_50, data = vnf_trailer_full)
summary(ch4_nox_50km)

ch4_nox_100km <- lm(avg_methane_eq_100 ~ ch4.night + co.night + co2.night + nox.night + benzene.night + wsp_ms.night + flare_wd_night_100 + flare_count_100, data = vnf_trailer_full)
summary(ch4_nox_100km)
```

```{r}
# Variables for the model
response <- c('ch4', 'benzene', 'co', 'co2')
predictors_fixed <- c('wdr_deg.night', 'wsp_ms.night')
predictors_dist_var <- c('flare_wd_night', 'flare_count')
distances <- c(10, 20)

# Tibble to store the result
compound_flare_lm_result <- tibble(Compound = character(),
                                   Radius = numeric(),
                                   'Adj R-sq' = numeric())
for (trailer_compound in response) {
  for (distance in distances) {
    predictors_dist_var_temp <- paste0(predictors_dist_var, paste0('_', distance))
    formula_feature_str <- paste(c(predictors_fixed, predictors_dist_var_temp), collapse = ' + ')
    formula_str <- paste(paste0(trailer_compound, '.night'), formula_feature_str, sep = ' ~ ')
    formula <- as.formula(formula_str)
    
    model <- lm(formula, data = vnf_trailer_full)
    assign(paste0(trailer_compound, '_count_', distance, 'km'), model)
    summary <- summary(model)
    
    compound_flare_lm_result <- compound_flare_lm_result %>%
      add_row(Compound = trailer_compound,
              Radius = distance,
              'Adj R-sq' = summary$adj.r.squared)
  }
}
compound_flare_lm_result
```

```{r}
# Look at the models specifically
for (trailer_compound in response) {
  for (distance in distances) {
    cat('--------------Compound: ', toupper(trailer_compound), ', Radius: ', distance, '---------------', sep = '')
    print(summary(get(paste0(trailer_compound, '_count_', distance, 'km'))))
  }
}
```





