---
title: "WeatherProcess"
author: "William Zhang, Jerry"
date: "2024-09-04"
output: html_document
---
```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
```
## Reading in data
```{r}
csv_names <- list.files('../data/Weather/')
csv_names <- csv_names[endsWith(csv_names, '.csv')]

for (i in 1:length(csv_names)){
  new <- read_csv(paste0('../data/Weather/', csv_names[i]), col_types='d', col_select = -c(1))
  new <- new %>%
    slice(2:(n() - 8))
  if (i == 1){
    full <- new
  } else {
    full <- full %>%
      bind_rows(new)
  }
}
```
## Cleaning
```{r}
# Download from https://aqi.air.env.nm.gov/StationReportFast.aspx?ST_ID=35#
# credit to Jerry Wu for some of the code here
weather <- full %>% select(-c(PM25, PM2.5_Archive))

# Convert date column to date type
weather$`Date Time` <- mdy_hm(weather$`Date Time`, tz = 'MST')
weather$`year` <- format(weather$`Date Time`, '%Y')

# Convert the rest to numeric
weather[2:14] <- sapply(weather[2:14],as.numeric)
sapply(weather, class)

# Rename the columns to match what openair uses
weather <- weather %>%
  rename('date' = `Date Time`, 'ws' = `Wind Speed S`, 'wd' = `Wind Dir S`,
         'nox' = `NOXppb`, 'no2' = `NO2ppb`, 'o3' = `O3`, 'no' = `NOppb`)
```

```{r}
# Saving
# Note that the variables are mostly covered in the trailer dataset, might need adjustments later
saveRDS(weather, "WeatherProcessed.rds")
```

