---
title: "FlaringProcess"
author: "William Zhang"
date: "2023-09-28"
output: html_document
---
```{r}
library(geosphere)
library(sf)
library(tools)
library(tidyverse)
```

## Reading data
```{r}
wells_clean <- readRDS("../data/wells/cleaned_wells_cb.rds")
wells_prod <- readRDS("../data/wells/cb_wells_prod.rds")
```

```{r}
# Location of trailer
# kmz <- file_path_as_absolute("../data/Passive sampler network Permian 3.kmz")
# 
# kmz <- st_read(unzip(kmz))
```


## Cleaning and Processing
Want to obtain monthly oil and gas production of all wells/prod within buffers loving site
```{r}
# filter distance
loving_lonlat <- c(-104.1089, 32.2961) 
loving_lonlat_sf <- st_sfc(st_point(loving_lonlat), crs = 4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

wells_prod <- wells_prod %>%
  st_as_sf(coords = c('uog_lon', 'uog_lat'), remove = F) %>%
  st_set_crs(4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

wells_prod <- wells_prod %>%
  mutate(distToLovi = c(drop_units(st_distance(wells_prod, loving_lonlat_sf)))/1000) %>% 
  st_drop_geometry() %>%
  select(-c("spud_date", "completion_date", "first_prod_date", "last_prod_date", "Operator.Company.Name"))

# Look at only conventional drilling by drill_type == 'V'
wells_prod_conv <- wells_prod %>%
  filter(drill_type == 'V')
```


```{r}
labels <- c('Conventional & Active during sampling', 'Conventional & Inactive during sampling', 'Unconventional & Active during sampling', 'Unconventional & Inactive during sampling')
# Create some binary variables for well type
# 1. Conventional well that produced between (including) May 2023, May 2024 (Red)
# 2. Conventional well that did not produce between ^ (Green)
# 3. Unconventional well that produced between ^ (Blue)
# 4. Unconventional well that did not produce between ^ (Purple)
# The wells taken into consideration are wells that produced sometime on or after 2010
wells_prod_wtype <- wells_prod %>%
  mutate(type = case_when(between(prod_date, as.Date('2023-05-01'), as.Date('2024-05-01')) & 
                            drill_type == 'V' ~ 1,
                          !between(prod_date, as.Date('2023-05-01'), as.Date('2024-05-01')) & 
                            drill_type == 'V' ~ 2,
                          between(prod_date, as.Date('2023-05-01'), as.Date('2024-05-01')) & 
                            drill_type != 'V' ~ 3,
                          !between(prod_date, as.Date('2023-05-01'), as.Date('2024-05-01')) & 
                            drill_type != 'V' ~ 4,
                          .default = 5))

wells_prod_viz_df <- wells_prod_wtype %>%
  group_by(api, uog_lon, uog_lat, distToLovi) %>%
  summarise(type = min(type)) %>%
  distinct()

count_table <- wells_prod_viz_df %>% group_by(type)%>% 
  summarise(#n = n(), 
            `n_50km` = sum(distToLovi<=50),
            `n_40km` = sum(distToLovi<=40),
            `n_30km` = sum(distToLovi<=30),
            `n_20km` = sum(distToLovi<=20),
            `n_10km` = sum(distToLovi<=10),
            `n_5km` = sum(distToLovi<=5)) %>%
  cbind(labels) %>% 
  mutate(type=labels) %>% 
  select(type, `n_50km`, `n_40km`, `n_30km`, `n_20km`, `n_10km`, `n_5km`) %>%
  add_row(tibble(type = 'Total', 
                 #n = nrow(wells_prod_viz_df),
                 `n_50km` = sum(wells_prod_viz_df$distToLovi <= 50),
                 `n_40km` = sum(wells_prod_viz_df$distToLovi <= 40),
                 `n_30km` = sum(wells_prod_viz_df$distToLovi <= 30),
                 `n_20km` = sum(wells_prod_viz_df$distToLovi <= 20),
                 `n_10km` = sum(wells_prod_viz_df$distToLovi <= 10),
                 `n_5km` = sum(wells_prod_viz_df$distToLovi <= 5)))

count_table
#write_csv(count_table, 'count_table.csv')
```

```{r}
# filter distance
wells_prod <- wells_prod %>% filter(distToLovi <= 50) %>% select(-c("drill_type", "uog_lon", "uog_lat", "well_status_p", "well_status", "prod_type_p", "production_type"))

wells_prod_conv <- wells_prod_conv %>% filter(distToLovi <= 50) %>% select(-c("drill_type", "uog_lon", "uog_lat", "well_status_p", "well_status", "prod_type_p", "production_type"))
```


### 20230101 to current - for Loving site
```{r}
wells_prod_0301 <- wells_prod %>% filter(prod_date >= "2023-05-01")
# replace NA with 0
wells_prod_0301$monthly_oil[is.na(wells_prod_0301$monthly_oil)] <- 0
wells_prod_0301$monthly_gas[is.na(wells_prod_0301$monthly_gas)] <- 0

wells_prod_conv_0301 <- wells_prod_conv %>% filter(prod_date >= "2023-05-01")
# replace NA with 0
wells_prod_conv_0301$monthly_oil[is.na(wells_prod_conv_0301$monthly_oil)] <- 0
wells_prod_conv_0301$monthly_gas[is.na(wells_prod_conv_0301$monthly_gas)] <- 0
```

```{r}
# Look at monthly prod for conventional vs unconventional
# Unconventional
wells_prod_0301 %>% group_by(prod_date) %>% 
  filter(prod_date>='2023-05-01') %>%
  summarize(monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas)) %>%
  print(n=20)

# Conventional
wells_prod_conv_0301 %>% group_by(prod_date) %>% 
  filter(prod_date>='2023-05-01') %>%
  summarize(monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas)) %>%
  print(n=20)
```



```{r}
# Group by date and dist
wells_prod_0301 <- wells_prod_0301 %>% group_by(prod_date, distToLovi) %>% 
  summarize(n = n(),
            monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas))

wells_prod_conv_0301 <- wells_prod_conv_0301 %>% group_by(prod_date, distToLovi) %>% 
  summarize(n = n(),
            monthly_oil = sum(monthly_oil),
            monthly_gas = sum(monthly_gas))
```

```{r}
# group by buffers around LNM

buffers <- c(5, 10, 20, 30, 40, 50)

assign_buffer <- function(dist) {
  cut(dist,
      breaks = c(-Inf, buffers),   
      labels = paste0("<= ", buffers, " km"),
      right = TRUE)
}


wells_prod_0301_grouped <- wells_prod_0301 %>%
  mutate(buffer = assign_buffer(distToLovi)) %>%
  group_by(prod_date, buffer) %>%
  summarize(n = n(),
            monthly_oil = sum(monthly_oil, na.rm = TRUE),
            monthly_gas = sum(monthly_gas, na.rm = TRUE),
            .groups = "drop")


wells_prod_conv_0301_grouped <- wells_prod_conv_0301 %>%
  mutate(buffer = assign_buffer(distToLovi)) %>%
  group_by(prod_date, buffer) %>%
  summarize(n = n(),
            monthly_oil = sum(monthly_oil, na.rm = TRUE),
            monthly_gas = sum(monthly_gas, na.rm = TRUE),
            .groups = "drop")
```

```{r}
# get totals

wells_prod_0301_total <- wells_prod_0301 %>%
  mutate(buffer = assign_buffer(distToLovi)) %>%
  group_by(buffer) %>%
  summarize(n = n(),
            monthly_oil = sum(monthly_oil, na.rm = TRUE)/1000000,
            monthly_gas = sum(monthly_gas, na.rm = TRUE)/1000000,
            .groups = "drop")

wells_prod_conv_0301_total <- wells_prod_conv_0301 %>%
  mutate(buffer = assign_buffer(distToLovi)) %>%
  group_by(buffer) %>%
  summarize(n = n(),
            monthly_oil = sum(monthly_oil, na.rm = TRUE)/1000000,
            monthly_gas = sum(monthly_gas, na.rm = TRUE)/1000000,
            .groups = "drop")
```


```{r}
# save to RDS
saveRDS(wells_prod_0301, "../data/processed_data/WellsProcessed20250909.rds")
```

