---
title: "Merged data visualisations"
output: html_document
date: "2024-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(zoo)
library(htmlwidgets)
library(openair)
library(leaflet)
```

# Load in merged data
```{r}
hourly_data <- readRDS("../DataProcessing/Trailer_hourly_merge_20240905.rds")
```

# Time series for ozone
```{r}
hourly_ozone <- hourly_data %>%
  arrange(time_utc) %>%
  mutate(o3_8h = rollmean(.$o3,
                                k = 8,
                                fill = NA,
                                align = "center")) %>%
  select(day, time_utc, o3, o3_8h) %>%
  filter(!is.na(o3_8h))

hourly_ozone %>%
  ggplot(aes(x = time_utc, group = 1)) + 
  geom_line(aes(y = o3_8h), linewidth=0.4, color = 'skyblue') +
  geom_hline(yintercept = 70, color = 'orange', linetype='dashed') +
  scale_x_discrete(breaks = hourly_ozone$time_utc[c(1, 4960, length(hourly_ozone$time_utc))], labels = hourly_ozone$day[c(1, 4960, length(hourly_ozone$day))]) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = '8-hour rolling mean of Ozone', x = 'Time', y = 'Ozone')

sum(hourly_ozone$o3_8h > 70.1)
```


# Other
```{r}
radio <- c('rd_particle_B', 'radon_B', 'radon_pCi', 'rd_particle_pCi')
h2s_so2 <- c('h2s', 'so2')
for (i in 1:length(radio)){
  for (j in 1:length(h2s_so2)) {
    cor <- cor(hourly_data %>% pull(radio[i]), hourly_data %>% pull(h2s_so2[j]), use = 'complete.obs')
    print(str_glue("Correlation between {radio[i]} and {h2s_so2[j]}: {round(cor, 4)}"))
  }
}
```

# DJB Well map
```{r}
wells_djb <- read_csv('../data/DJB well Well Headers.CSV')
  
cleaned_wells_djb <- wells_djb %>%
  dplyr::select(api = API14, drill_type = `Drill Type`, spud_date = `Spud Date`, 
                completion_date = `Completion Date`, 
                first_prod_date = `First Prod Date`, 
                last_prod_date = `Last Prod Date`, 
                well_status = `Well Status`, 
                production_type = `Production Type`,
                uog_lon = `Surface Hole Longitude (WGS84)`, 
                uog_lat = `Surface Hole Latitude (WGS84)`,
                Operator.Company.Name = `Operator Company Name`)

site_coords <- tibble(name = c('LUR', 'LLG', 'BRZ', 'ECC', 'BNP'),
                      lat = c(40.1762235, 40.1607039, 40.0699783, 40.0402277, 39.9814076),
                      lon = c(-105.0476608, -105.1461437, -105.2202754, -105.0520854, -105.0064873))
# Wells map
map <- leaflet() %>%
        addTiles() %>% 
        addProviderTiles("Esri.WorldImagery") %>% 
        addProviderTiles("CartoDB.PositronOnlyLabels") %>%  
        addCircleMarkers(data = cleaned_wells_djb, lng=~uog_lon, lat=~uog_lat, 
                         fillOpacity = 0.9, radius = 2, weight = 1, color="cyan") %>%
        addCircleMarkers(data = site_coords, lng=~lon, lat=~lat, radius=10,color="yellow", 
                         fillColor = "yellow", fillOpacity = 1,
                         label = ~name, 
                         labelOptions = 
                           labelOptions(noHide = TRUE, direction = 'bottom', offset = c(0, 8),
                                        style = list(
                                                     "color" = "black",
                                                     "font-family" = "serif",
                                                     "font-size" = "14px"
                                                    )))%>%
        addScaleBar("bottomright")
map
saveWidget(map, file="djb_map.html")
```

# Plots for Ethane
```{r}
ethane <- hourly_data %>%
  select(all_of(c('time_utc', 'ethane', 'wdr_deg', 'wsp_ms'))) %>%
  mutate(datetime_mountain = with_tz(as.POSIXct(time_utc, tz = 'UTC', 
                                                format = "%Y-%m-%d %H:%M:%OS"), 
                                     tzone = "America/Denver")) %>%
  filter(date(datetime_mountain) >= '2023-05-01') %>%
  na.omit()
```

## Polar plot
```{r}
polarPlot(ethane %>%
            rename(ws = 'wsp_ms',
                   wd = 'wdr_deg'), 
          pollutant = 'ethane', 
          x= 'ws', 
          wd = 'wd',
          min.bin = 2,
          key.header = "Mean", 
          key.footer = 'Ethane')
```

```{r}
# beyond 90th percentile
ethane_90 <- ethane %>% filter(ethane > quantile(ethane, probs = 0.9))
polarPlot(ethane_90 %>%
            rename(ws = 'wsp_ms',
                   wd = 'wdr_deg'), 
          pollutant = 'ethane', 
          x= 'ws', 
          wd = 'wd',
          min.bin = 2,
          key.header = "Mean", 
          key.footer = 'Ethane')
```

## Diurnal boxplot
```{r}
# filter filter for diurnal measurements (11am - 5pm)
ethane_diurnal <- ethane %>%
  mutate(hour = hour(datetime_mountain))

ggplot(ethane_diurnal, aes(x = factor(hour), y = ethane)) +
  stat_boxplot(geom ='errorbar') + 
  geom_boxplot(fill = 'wheat1', outliers = T, size = 0.3, outlier.shape = 16) +
  coord_cartesian(ylim = c(0, 2100)) +
  scale_y_continuous(
    limits = c(0, NA),
    breaks = seq(0, 2100, length.out = 5) ,
    expand = expansion(mult = c(0))
  ) +
  labs(title = '', x = "Hour of day", y = "Ethane") +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 12),
    # Smaller title text
    axis.title = element_text(size = 10),
    # Smaller axis labels
    axis.text = element_text(size = 10),
    # Smaller x and y tick labels
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

# Pentane ratio
```{r}
pentane <- hourly_data %>%
  mutate(datetime_mountain = with_tz(as.POSIXct(time_utc, tz = 'UTC', 
                                              format = "%Y-%m-%d %H:%M:%OS"), 
                                   tzone = "America/Denver")) %>%
  filter(date(datetime_mountain) >= '2023-05-01') %>%
  select(all_of(c('i-pentane', 'n-pentane', 'wdr_deg'))) %>%
  mutate(pentane_ratio = `i-pentane`/`n-pentane`,
         wd = round(wdr_deg, -1)) %>%
  mutate(wd = factor(wd, levels = sort(unique(wd)))) %>%
  na.omit()

every_second_label <- levels(pentane$wd)[seq(1, length(levels(pentane$wd)), by = 2)]

ggplot(pentane, aes(x = wd, y = pentane_ratio)) +
  stat_boxplot(geom ='errorbar') + 
  geom_boxplot(fill = 'wheat1', outliers = F, size = 0.3, outlier.shape = 16,) +
  coord_cartesian(ylim = c(0.8, 1.5)) +
  scale_x_discrete(breaks = every_second_label) +
  scale_y_continuous(
    limits = c(0.8, NA),
    breaks = seq(0.8, 1.5, length.out = 5) ,
    expand = expansion(mult = c(0))
  ) +
  labs(title = '', x = "Wind direction", y = "Pentane ratio") +
  theme_minimal() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 12),
    # Smaller title text
    axis.title = element_text(size = 10),
    # Smaller axis labels
    axis.text = element_text(size = 10),
    # Smaller x and y tick labels
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

# V3.5 flare map
```{r}
# load in clustered data
flare_v35 <- read_csv('../data/pb_vnf/flaring_v35_clustered.csv') 
flare_v35 <- flare_v35 %>%
  mutate(noise = ifelse(cluster == -1, TRUE, FALSE))

flare_v35 <- flare_v35  %>%
  st_as_sf(coords = c('easting', 'northing'), remove = F) %>%
  st_set_crs("+proj=utm +zone=13 ellps=WGS84") %>%
  st_transform(4326) %>%
  mutate(lon = st_coordinates(.)[,1],
         lat = st_coordinates(.)[,2]) %>%
  st_drop_geometry()

flare_v35_plot <- leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>% 
  addProviderTiles("CartoDB.PositronOnlyLabels") %>%  
  addCircleMarkers(data = flare_v35, lng = ~lon, lat = ~lat, 
                   stroke = T, fillColor = ~ case_when(noise == TRUE ~ '#FFD700', 
                                                       .default = '#B22222'), radius = 2, weight = 1,
                   group = 'Flares', col='white', fillOpacity = 0.7) %>%
  addLegend(colors = c('#FFD700', '#B22222'), 
            labels = c('Noise', 'Clustered'),
            position = 'bottomleft')

flare_v35_plot
 
```

# Well location map (50KM) around
```{r}
# Part of code is copied from WellProcess.rmd
wells_clean <- readRDS("../data/wells/cleaned_wells_cb.rds")
wells_prod <- readRDS("../data/wells/cb_wells_prod.rds")

# filter distance
loving_lonlat <- c(-104.1089, 32.2961) 
loving_lonlat_sf <- st_sfc(st_point(loving_lonlat), crs = 4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

wells_prod <- wells_prod %>%
  st_as_sf(coords = c('uog_lon', 'uog_lat'), remove = F) %>%
  st_set_crs(4326) %>%
  st_transform("+proj=utm +zone=13 ellps=WGS84")

wells_prod <- wells_prod %>%
  mutate(distToLovi = c(drop_units(st_distance(wells_prod, loving_lonlat_sf)))/1000) %>% 
  st_drop_geometry() %>%
  select(-c("spud_date", "completion_date", "first_prod_date", "last_prod_date", "Operator.Company.Name"))

# Look at only conventional drilling by drill_type == 'V'
wells_prod_conv <- wells_prod %>%
  filter(drill_type == 'V')
```

```{r}
# Create some binary variables for well type
# 1. Conventional well that produced between (including) May 2023, June 2024 (Red)
# 2. Conventional well that did not produce between ^ (Green)
# 3. Unconventional well that produced between ^ (Blue)
# 4. Unconventional well that did not produce between ^ (Purple)
# The wells taken into consideration are wells that produced sometime on or after 2010
wells_prod <- wells_prod %>%
  mutate(type = case_when(between(prod_date, as.Date('2023-05-01'), as.Date('2024-06-01')) & 
                            drill_type == 'V' ~ 1,
                          !between(prod_date, as.Date('2023-05-01'), as.Date('2024-06-01')) & 
                            drill_type == 'V' ~ 2,
                          between(prod_date, as.Date('2023-05-01'), as.Date('2024-06-01')) & 
                            drill_type != 'V' ~ 3,
                          !between(prod_date, as.Date('2023-05-01'), as.Date('2024-06-01')) & 
                            drill_type != 'V' ~ 4,
                          .default = 5))

wells_prod_viz_df <- wells_prod %>%
  group_by(api, uog_lon, uog_lat, distToLovi) %>%
  summarise(type = min(type)) %>%
  distinct()
```

```{r}
labels <- c('Conventional & Active during sampling', 'Conventional & Inactive during sampling', 'Unconventional & Active during sampling', 'Unconventional & Inactive during sampling')

colors <- c('Red', 'Green', 'Blue', 'Purple')

wells_prod_viz_df <- split(wells_prod_viz_df, wells_prod_viz_df$type)

l <- leaflet(options = leafletOptions(zoomControl = TRUE,
                                 zoomSnap = 0.1,
                                 zoomDelta = 0.1,
                                 wheelPxPerZoomLevel = 120)) %>%
  addProviderTiles("Esri.WorldImagery") %>% 
  addProviderTiles("CartoDB.PositronOnlyLabels")

names(wells_prod_viz_df) %>%
  purrr::walk( function(df) {
    l <<- l %>%
      addCircles(data=wells_prod_viz_df[[df]],
                 lng=~uog_lon, lat=~uog_lat,
                 label=~as.character(api),
                 popup=~as.character(api),
                 fillColor = colors[as.numeric(df)],
                 stroke = T,  radius = 125, weight = 1, 
                 col= colors[as.numeric(df)], fillOpacity = 1,
                 group = labels[as.numeric(df)],
                 labelOptions = labelOptions(noHide = FALSE, direction = 'auto'))
  })

l <- l %>%
  addLegend(colors = colors, 
          labels = labels,
          position = 'bottomleft') %>%
  addLayersControl(
    overlayGroups = labels,
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  addScaleBar(
  position = c("bottomright"),
  options = scaleBarOptions()
) %>%
  addCircles(lng = loving_lonlat[1],
             lat = loving_lonlat[2],
             col= 'Yellow', 
             weight = 1,
             fillOpacity = 1,
             radius = 500)
l
saveWidget(l, file="well_map.html")
```

```{r}
wells_prod_viz_df <- wells_prod %>%
  group_by(api, uog_lon, uog_lat, distToLovi) %>%
  summarise(type = min(type)) %>%
  distinct()

count_table <- wells_prod_viz_df %>% group_by(type)%>% 
  summarise(n = n(), 
            `n_50km` = sum(distToLovi<=50),
            `n_40km` = sum(distToLovi<=40),
            `n_30km` = sum(distToLovi<=30),
            `n_20km` = sum(distToLovi<=20),
            `n_10km` = sum(distToLovi<=10),
            `n_5km` = sum(distToLovi<=5)) %>%
  cbind(labels) %>% 
  mutate(type=labels) %>% 
  select(type, n, `n_50km`, `n_40km`, `n_30km`, `n_20km`, `n_10km`, `n_5km`) %>%
  add_row(tibble(type = 'Total', 
                 n = nrow(wells_prod_viz_df),
                 `n_50km` = sum(wells_prod_viz_df$distToLovi <= 50),
                 `n_40km` = sum(wells_prod_viz_df$distToLovi <= 40),
                 `n_30km` = sum(wells_prod_viz_df$distToLovi <= 30),
                 `n_20km` = sum(wells_prod_viz_df$distToLovi <= 20),
                 `n_10km` = sum(wells_prod_viz_df$distToLovi <= 10),
                 `n_5km` = sum(wells_prod_viz_df$distToLovi <= 5)))

count_table
write_csv(count_table, 'count_table.csv')
```

```{r}
a <- wells_prod %>%
  group_by(prod_date, type) %>%
  filter(prod_date >= '2023-05-01', prod_date <= '2024-06-01') %>%
  summarize(
    monthly_oil = sum(monthly_oil, na.rm = T),
    monthly_gas = sum(monthly_gas, na.rm = T)
  ) %>%
  mutate(type = if_else(type == 1, 'Conventional', 'Unconventional'))

b <- wells_prod %>%
  filter(distToLovi <= 50) %>%
  group_by(prod_date, type) %>%
  filter(prod_date >= '2023-05-01', prod_date <= '2024-06-01') %>%
  summarize(
    monthly_oil_50km = sum(monthly_oil, na.rm = T),
    monthly_gas_50km = sum(monthly_gas, na.rm = T)
  ) %>%
  mutate(type = if_else(type == 1, 'Conventional', 'Unconventional'))

total <- left_join(
  wells_prod %>%
    group_by(prod_date) %>%
    filter(prod_date >= '2023-05-01', prod_date <= '2024-06-01') %>%
    summarize(
      monthly_oil = sum(monthly_oil, na.rm = T),
      monthly_gas = sum(monthly_gas, na.rm = T)
    )
  ,
  wells_prod %>%
    filter(distToLovi <= 50) %>% 
    group_by(prod_date) %>%
    filter(prod_date >= '2023-05-01', prod_date <= '2024-06-01') %>%
    summarize(
      monthly_oil_50km = sum(monthly_oil, na.rm = T),
      monthly_gas_50km = sum(monthly_gas, na.rm = T)
    )
) %>%
  mutate(type = 'Both') %>%
  relocate(prod_date, type)
total

c <- left_join(a, b) %>%
  left_join(total, join_by(prod_date), suffix = c("", "_total")) %>%
  mutate(oil_percent = round(monthly_oil/monthly_oil_total*100, 2),
         gas_percent = round(monthly_gas/monthly_gas_total*100, 2),
         oil_percent_50km = round(monthly_oil_50km/monthly_oil_50km_total*100, 2),
         gas_percent_50km = round(monthly_gas_50km/monthly_gas_50km_total*100, 2)) %>%
  mutate(monthly_oil = as.character(str_glue("{monthly_oil} ({oil_percent}%)")),
         monthly_gas = as.character(str_glue("{monthly_gas} ({gas_percent}%)")),
         monthly_oil_50km = as.character(str_glue("{monthly_oil_50km} ({oil_percent_50km}%)")),
         monthly_gas_50km = as.character(str_glue("{monthly_gas_50km} ({gas_percent_50km}%)"))) %>%
  select(-ends_with("_total"), -contains('_percent')) %>%
  bind_rows(total %>% mutate(across(contains('monthly'), as.character))) %>%
  arrange(prod_date)
c
#write_csv(c, 'production_table.csv')
```
```{r}
# Version 2: Only 50km.
both <- wells_prod %>%
    filter(distToLovi <= 50) %>% 
    group_by(prod_date) %>%
    filter(prod_date >= '2023-05-01', prod_date <= '2024-06-01') %>%
    summarize(
      monthly_oil_50km = sum(monthly_oil, na.rm = T),
      monthly_gas_50km = sum(monthly_gas, na.rm = T)
    ) %>%
  mutate(type = 'Both',
         prod_date = as.character(prod_date)) %>%
  relocate(prod_date, type)

both <- both %>%
  add_row(tibble(prod_date = 'Total', 
                 type = 'Both', 
                 monthly_oil_50km = sum(both$monthly_oil_50km), 
                 monthly_gas_50km = sum(both$monthly_gas_50km)))

b <- b %>%
  ungroup() %>%
  mutate(prod_date = as.character(prod_date)) %>%
  add_row(b %>% 
            group_by(type) %>% 
            summarise(monthly_oil_50km = sum(monthly_oil_50km),
                      monthly_gas_50km = sum(monthly_gas_50km)) %>%
            mutate(prod_date = 'Total'))


d <- left_join(b, both, join_by(prod_date), suffix = c("", "_both"))

d <- d %>%
  mutate(oil_percent_50km = round(monthly_oil_50km/monthly_oil_50km_both*100, 2),
         gas_percent_50km = round(monthly_gas_50km/monthly_gas_50km_both*100, 2)) %>%
  mutate(monthly_oil_50km = as.character(str_glue("{monthly_oil_50km} ({oil_percent_50km}%)")),
         monthly_gas_50km = as.character(str_glue("{monthly_gas_50km} ({gas_percent_50km}%)"))) %>%
  select(-ends_with("_both"), -contains('_percent')) %>%
  bind_rows(both %>% mutate(across(contains('monthly'), as.character))) %>%
  arrange(prod_date)
d
write_csv(d, 'production_table.csv')
```

